---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: application-01
    app.kubernetes.io/part-of: application-01
    apps.open-cluster-management.io/reconcile-rate: high
  name: instal-nmstate-operator-placement
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: name
          operator: In
          values:
          - local-cluster
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists