---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-nmstate
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      matchLabels:
        local-cluster: 'true'
  # remediationAction: inform
  remediationAction: enforce
  # complianceType: mustonlyhave
  complianceType: musthave
policies:
  - name: install-nmstate
    manifests:
      - path: instal-nmstate-operator-placement.yaml
      - path: instal-nmstate-operator-placementbinding.yaml
      - path: policy-generator-config.yaml
