apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: instal-nmstate-operator
  namespace: policies
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            name: nmstate-operator
            namespace: openshift-nmstate
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: None
          versions:
