apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    kubernetes.io/metadata.name: openshift-logging
    clusterresourceoverrides.admission.autoscaling.openshift.io/enabled: "true"
  annotations:
    quota.openshift.io/cluster-resource-override-enabled: "false"
---
apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise
  labels:
    kubernetes.io/metadata.name: quay-enterprise
  annotations:
    quota.openshift.io/cluster-resource-override-enabled: "false"
