apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    kubernetes.io/metadata.name: openshift-logging
  annotations:
    quota.openshift.io/cluster-resource-override-enabled: "false"
