---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namePrefix: eccolo-

# configMapGenerator:
#   - name: cluster-labels-config-local-cluster
#     literals:
#       - clusterSelectorLabel=local-cluster

# vars:
#   - name: CLUSTER_SELECTOR_LABEL
#     objref:
#       kind: ConfigMap
#       name: cluster-labels-config-local-cluster
#       apiVersion: v1
#     fieldref:
#       fieldpath: data.clusterSelectorLabel

# configMapGenerator:
#   - name: cluster-labels-config
#     envs: [environment.properties]

# vars:
# - name: CLUSTER_SELECTOR_LABEL
#   objref: { kind: ConfigMap, name: cluster-labels-config, apiVersion: v1 }
#   fieldref: { fieldpath: data.CLUSTER_SELECTOR_LABEL }

configMapGenerator:
  - name: cm-policy-vars
    literals:
      - POLICY_LABEL_ORIGIN=kustomize

resources:
- overcommitment
- kubeletconfig
- zorro
#- test
#- logging