apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# configMapGenerator:
#   - name: cluster-labels-config
#     envs: [environment.properties]

# vars:
# - name: CLUSTER_SELECTOR_LABEL
#   objref: { kind: ConfigMap, name: cluster-labels-config, apiVersion: v1 }
#   fieldref: { fieldpath: data.CLUSTER_SELECTOR_LABEL }

resources:
  - polycy-ns-cartella-3.yaml
  - placement-local-cluster.yaml
  - placementbinding-local-cluster.yaml