apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: polycy-ns-cartella-3
  namespace: policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: polycy-ns-cartella-3
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                kubernetes.io/metadata.name: test
                mylabel: CLUSTER_SELECTOR_LABEL
              name: cartella-3
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
        severity: high
  remediationAction: enforce
