---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: logging-policy
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      matchLabels:
        local-cluster: 'true'
  # remediationAction: inform
  remediationAction: enforce
  # complianceType: mustonlyhave
  complianceType: musthave
policies:
  - name: logging-policy
    manifests:
      - path: logging-policy.yaml